expose:
  type: nodePort
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-tls
  nodePort:
    ports:
      https:
        port: 30003

persistence:
  enabled: true

externalURL: https://harbor.local:30003

# Not set here for obvious security reasons! :)
# harborAdminPassword:


# Deprecated?!