expose:
  type: ingress
  ingress:
    className: nginx
    hosts:
      core: harbor.home
      notary: notary.harbor.home
    annotations:
      cert-manager.io/cluster-issuer: "my-ca-issuer"
  tls:
    certSource: secret
    enabled: true
    secret:
      secretName: harbor-tls

externalURL: https://harbor.home

persistence:
  enabled: true
